[package]
name = "chalkboard"
version = "0.1.0"
edition = "2021"

[dependencies]
genimage = { path = "../../genimage" }
geometry = { package = "chalkboard-geometry", path = "../chalkboard-geometry" }
